### PR TITLE
Signature and API changes for Recurly.js 2.1.

### PR DESCRIPTION
**Pull request by joelhegg**
http://docs.recurly.com/api/recurlyjs/upgrading

### CODE REVIEW

**Comment by tfoxcroft** [comment]
Hi Joel, 

Thank you for this, we are currently using API version 1 but will certainly be looking at upgrading to version 2 at some point. I've merged your changes and started cleaning up my JavaDocs, the README etc before uploading it to the central Maven repository.

I've tagged the previous working version which targeted API version 1. Is this what where looking to have in the Maven repository? Or are you happy getting version 2 to work before uploading?

Btw I've added 1 todo in RecurlyJS just to check on a minor issue with the timestamp. I will try to check up on this but you will likely have better knowledge.

Regards,
Terence

**Comment by tfoxcroft** [comment]
Btw - I'm new to working on projects outside of my work environment, so please feel free to let me know if I can help in any better ways or if I'm stepping on any toes or anything like that!

**Comment by joelhegg** [comment]
Hi Terence,

You're doing great. I don't normally contribute this much externally myself either.

I would just stick to the 2.1 version in the Maven repository. I don't think there would be much demand for an older version.

As far as the TODO, I actually added the /1000 to the timestamp because I was getting errors back from Recurly about my my request being expired without it.

Joel

**Comment by joelhegg** [comment]
One open issue is that we don't currently support the fetch() method here that's available in the PHP, Ruby, and Python Recurly.js libraries. It involves making a remote call and parsing the XML response. I'm not sure what the right solution is yet. It might involve integrating with https://github.com/Kwanzoo/recurly-client-java.

**Comment by joelhegg** [comment]
FYI, I was able to get the fetch support I needed from https://github.com/killbilling/recurly-java-library. It doesn't seem like there's any reason to add fetch support to this library.

**Pull request merged**
